name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: "Content"
  - type: markdown
    attributes:
      value: |
        # 🐙🐬🐸🦀🦈

        ## 🐙🐙🐙 たこ 🐙🐙🐙

        🐙🐙🐙🐙🐙 🐙🐙🐙🐙🐙 🐙🐙🐙🐙🐙
        🐙🐙🐙🐙🐙 🐙🐙🐙🐙🐙 🐙🐙🐙🐙🐙
        🐙🐙🐙🐙🐙 🐙🐙🐙🐙🐙 🐙🐙🐙🐙🐙
        🐙🐙🐙🐙🐙 🐙🐙🐙🐙🐙 🐙🐙🐙🐙🐙
        🐙🐙🐙🐙🐙 🐙🐙🐙🐙🐙 🐙🐙🐙🐙🐙

        ## 🐬🐬🐬 いるか 🐬🐬🐬

        🐬🐬🐬🐬🐬 🐬🐬🐬🐬🐬 🐬🐬🐬🐬🐬
        🐬🐬🐬🐬🐬 🐬🐬🐬🐬🐬 🐬🐬🐬🐬🐬
        🐬🐬🐬🐬🐬 🐬🐬🐬🐬🐬 🐬🐬🐬🐬🐬
        🐬🐬🐬🐬🐬 🐬🐬🐬🐬🐬 🐬🐬🐬🐬🐬
        🐬🐬🐬🐬🐬 🐬🐬🐬🐬🐬 🐬🐬🐬🐬🐬

        ## 🐸🐸🐸 かえる 🐸🐸🐸

        🐸🐸🐸🐸🐸 🐸🐸🐸🐸🐸 🐸🐸🐸🐸🐸
        🐸🐸🐸🐸🐸 🐸🐸🐸🐸🐸 🐸🐸🐸🐸🐸
        🐸🐸🐸🐸🐸 🐸🐸🐸🐸🐸 🐸🐸🐸🐸🐸
        🐸🐸🐸🐸🐸 🐸🐸🐸🐸🐸 🐸🐸🐸🐸🐸
        🐸🐸🐸🐸🐸 🐸🐸🐸🐸🐸 🐸🐸🐸🐸🐸

        ## 🦀🦀🦀 かに 🦀🦀🦀

        🦀🦀🦀🦀🦀 🦀🦀🦀🦀🦀 🦀🦀🦀🦀🦀
        🦀🦀🦀🦀🦀 🦀🦀🦀🦀🦀 🦀🦀🦀🦀🦀
        🦀🦀🦀🦀🦀 🦀🦀🦀🦀🦀 🦀🦀🦀🦀🦀
        🦀🦀🦀🦀🦀 🦀🦀🦀🦀🦀 🦀🦀🦀🦀🦀
        🦀🦀🦀🦀🦀 🦀🦀🦀🦀🦀 🦀🦀🦀🦀🦀

        ## 🦈🦈🦈 さめ 🦈🦈🦈

        🦈🦈🦈🦈🦈 🦈🦈🦈🦈🦈 🦈🦈🦈🦈🦈
        🦈🦈🦈🦈🦈 🦈🦈🦈🦈🦈 🦈🦈🦈🦈🦈
        🦈🦈🦈🦈🦈 🦈🦈🦈🦈🦈 🦈🦈🦈🦈🦈
        🦈🦈🦈🦈🦈 🦈🦈🦈🦈🦈 🦈🦈🦈🦈🦈
        🦈🦈🦈🦈🦈 🦈🦈🦈🦈🦈 🦈🦈🦈🦈🦈
